### ISSUE TITLE
Nature Scrape Failed in get_license

### ISSUE THREAD

**Issue by lwashington3** [MaterialEyes/exsclaim2.0#2]
Tried querying open access articles in Nature regarding renewable energy using the [development API](https:api.exsclaim-dev.materialeyes.org) v2.1.0b9. Here's the query and result:

```json
{
  "name":"time_check",
  "journal_family":"Nature",
  "maximum_scraped":"5",
  "sortby":"relevant",
  "term": "renewable energy",
  "synonyms": [],
  "save_format":["boxes"],
  "open_access": true,
  "llm":"gpt-3.5-turbo",
  "model_key": "{my_key_here}",
}
```

```shell
07/22/2024 11:42:34	/usr/local/lib/python3.11/site-packages/exsclaim/tool.py:184: Running Journal Scraper
2024-07-22T16:42:34.908970507Z 
07/22/2024 11:42:41	/usr/local/lib/python3.11/site-packages/exsclaim/journal.py:422: GET request: https://www.nature.com/search?q=renewable%20energy&&&date_range=&journal=&order=relevance
07/22/2024 11:42:44	/usr/local/lib/python3.11/site-packages/exsclaim/pipeline.py:248: 'NoneType' object is not subscriptable
2024-07-22T16:42:44.093734475Z Traceback (most recent call last):
2024-07-22T16:42:44.093740773Z   File "/usr/local/lib/python3.11/site-packages/exsclaim/pipeline.py", line 203, in run
2024-07-22T16:42:44.093745635Z     self.exsclaim_dict = tool.run(self.query_dict, self.exsclaim_dict)
2024-07-22T16:42:44.093749964Z                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-22T16:42:44.093754188Z   File "/usr/local/lib/python3.11/site-packages/exsclaim/tool.py", line 240, in run
2024-07-22T16:42:44.093758821Z     articles = journal.get_article_extensions()
2024-07-22T16:42:44.093762949Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-22T16:42:44.093767434Z   File "/usr/local/lib/python3.11/site-packages/exsclaim/journal.py", line 479, in get_article_extensions
2024-07-22T16:42:44.093772361Z     new_article_paths = self.get_articles_from_search_url(search_url)
2024-07-22T16:42:44.093776806Z                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/exsclaim/journal.py", line 471, in get_articles_from_search_url
2024-07-22T16:42:44.093785881Z     return self.temporary_browser(get_articles_search_url_from_playwright, search_url=search_url)
2024-07-22T16:42:44.093800649Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-22T16:42:44.093804747Z   File "/usr/local/lib/python3.11/site-packages/exsclaim/browser.py", line 26, in temporary_browser
    values = function(page, browser=browser, **kwargs)
2024-07-22T16:42:44.093812862Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-22T16:42:44.093816445Z   File "/usr/local/lib/python3.11/site-packages/exsclaim/journal.py", line 456, in get_articles_search_url_from_playwright
2024-07-22T16:42:44.093820297Z     self.open and not self.is_link_to_open_article(tag)
2024-07-22T16:42:44.093823927Z                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-22T16:42:44.093827708Z   File "/usr/local/lib/python3.11/site-packages/exsclaim/journal.py", line 1011, in is_link_to_open_article
    return self.get_license(locator.page)[0]
2024-07-22T16:42:44.093836597Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-22T16:42:44.093840214Z   File "/usr/local/lib/python3.11/site-packages/exsclaim/journal.py", line 987, in get_license
2024-07-22T16:42:44.093843882Z     _copyright = parsed["content"]["attributes"]["copyright"]
2024-07-22T16:42:44.093847937Z                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
2024-07-22T16:42:44.093852357Z TypeError: 'NoneType' object is not subscriptable
```

**Comment by lwashington3** [comment]
The same query worked when `open_access` was changed to false.
